-- Create Customers table
Create table Customers (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IMAGE VARCHAR(50),
    NAME VARCHAR(30),
    BIRTHDAY VARCHAR(6),
    GENDER VARCHAR(10),
    JOB VARCHAR(30)
);

-- DB 사용
USE CRM;

-- 구조 확인
DESC CUSTOMERS;

-- ALTER COLUMN NOT NULL
ALTER TABLE CUSTOMERS MODIFY NAME VARCHAR(30) NOT NULL;
ALTER TABLE CUSTOMERS MODIFY BIRTHDAY VARCHAR(6) NOT NULL;
ALTER TABLE CUSTOMERS MODIFY GENDER VARCHAR(10) NOT NULL;
ALTER TABLE CUSTOMERS MODIFY JOB VARCHAR(30) NOT NULL;

-- 데이터 인서트
INSERT INTO CUSTOMERS
VALUES (1, 'https://placeimg.com/64/64/1', '문나리', '981028', '여자', '학생');

-- 삭제 기능 생성
ALTER TABLE CUSTOMERS ADD CREATEDDATE DATETIME;
ALTER TABLE CUSTOMERS ADD DELETEDDATE DATETIME;
ALTER TABLE CUSTOMERS ADD ISDELETED INT;